---
title: "Projeto de pesquisa"
autor: "Wagner Jorcuvich"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    collapsed: true
    number_sections: true
    toc_depth: 6
---

# Projeto de pesquisa

## Desenho Geral do Estudo

### Sujeito e Objeto

Neonatos hospitalares readmitidos a termo saudável.
Caracterização do tempo de internação ao nascer.

### Tema e Problema

Tempo de permanência ao nascer e risco de readmissão.
Crianças nascidas em hosptital que ficam internadas menos tempo tem maior risco de readmissão?

#### Amostra e Delimitações

Nascidos vivos em hospitais paranaense com bases disponiíves no SINASC, que fororam readmitidos em hospitais do mesmo estado, com base no SIH, ano base 2019.

### Hipótese


### Objetivos
#### Objetivos Geral

Investigar a prevalência de readmissões de neonatos, associando a tempo de internação.

#### Objetivos Específicos

2. Identificar o perfil nos neonatos readmitidos no SIH e associá-los à interação.
3. Associar os readmitidos à suas condições de nascimento no SINASC.
4. Avaliar as características obstéticas, complicações e doêncas.
5. Investigar a prevalência de readmissões, de acordo com tempo de internação.
7. Quantificar o risco de readmissão baseado em tempo de permanência. 

### Revisão da literatura

#### Seleção em Banco de Artigos

Preferencialmente artigos, utilizando o pesquisador consolidado CAFE-Capes, limitado a 15 anos.

##### Problema da pesquisa

Eixo de Palavras

* Patient readmission
* Neonatal
* Newborn infant
* Neonatology
* Hospitalization
* Cesarean delivery
* Lenglh of stay
* Hostpial record
* DATASUS
* SINASC
* SIH
* Hospital Records

##### Técnicas

* Record Linkage
* Epidemiological methods
* Medical record linkage
* Bias
* Data linkage
* DATASUS


### Cronograma
<!---
### Desenho metodológico
### Restultados esperados
### Possíveis impactos

### Contribuição Científica
-->



# Importação de bancos de dados

## Preparando o R

Os *datasets* baixados no DATASUS tem a extensão `.dbc`. Foi necessáro instalar umma biblioteca para leitura, utilizei o `read.dbc`[^1].

[^1]: CRAM disponível em <https://cran.r-project.org/web/packages/read.dbc/index.html>


Carregando a biblioteca:
```{r }
library(read.dbc)
```

## Bases

### Inclusão da base SIH

Os dados sobre internações hospitalares foram extraídos do Sistema de Infomações Hospitalares (SIA), um banco de dados administrativo que contém informações de todas as internações em hospitais do Sistema Único de Saúde (SUS) no Brasil. Os registros de admissão contêm diagnósticos clínicos codificados de acordo com a 10ª Revisão da Classificação Estatística Internacional de Doenças e Problemas Relacionados à Saúde (CID-10)[^2].


Nesta base, filtrando pelo CID-10, é possível separar 

XV	O00-O99	Gravidez, parto e puerpério.
XVI	P00-P96	Algumas afecções originadas no período perinatal.



### Inclusão da base SINASC

Devida a insuficiência de informações na base SIH como situação conjugal e raça/cor da mãe, tipo de gravidez, tipo de apresentação do feto, indução do parto e doença congênita percebida ao nascer, foi necessário lançar mão da base  Sistema de Informação sobre Nascidos Vivos (SINASC)[^2].

[^2]: Bases do DATASUS <http://www2.datasus.gov.br/DATASUS/index.php?area=0901>

# Escolha da População

A população do estudo foi retirada de uma coorte de mães e neonatos cujos partos e readmissões foram capturados no SIH e a alta pós-natal ocorreu entre janeiro de 2014 e dezembro de 2016.



